### ISSUE TITLE
connect  timeout

### ISSUE THREAD

**Issue by deboLing** [wu928320442/EasyAndroid#3]
apply from:'https://cdn.rawgit.com/Jude95/JCenter/master/install.gradle'
apply from:'https://cdn.rawgit.com/Jude95/JCenter/master/bintray.gradle'

项目构建失败

**Comment by wu928320442** [comment]
应该是我当时提交到JCenter使用到的一个在线插件Gradle 你平时去掉这些配置就好了

**Comment by deboLing** [comment]
ok , thanks
